export const FURNITURES_LOADING = "FURNITURES_LOADING";
export const ADD_FURNITURES = "ADD_FURNITURES";
export const FURNITURES_FAILED = "FURNITURES_FAILED";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const ADD_FAVORITE = "ADD_FAVORITE";
